### ISSUE TITLE
[Bug]: Arms Race update and Mapgroup

### ISSUE THREAD

**Issue by pnallinger** [kus/csgo-modded-server#60]
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

Other (please specify)

### Are you trying to host online or on LAN?

Online on a game hosting network (please specify host)

### Metamod:Source Version

uptodate

### Metamod:Source Plugins loaded

uptodate

### CounterStrikeSharp Version

uptodate

### CounterStrikeSharp Plugins loaded

uptodate

### What is the bug

Arms Race loads GunGame maps (mg_gg)
I added a new Map Group (mg_ar) and changed the config so you can play on the new Arms Race maps and dont have to start this mode everytime. also i changed the time and Bots config. I am relativly new to GitHUB. Would you like a code Push or the config files? I want to contribute.

**Comment by kus** [comment]
Hi @pnallinger Arms Race and GunGame are the same thing GunGame is just a mod of how it used to work in CS:S CS:GO Arms Race was built to copy GunGame, so that's why it uses the same maps.

What did you change with the bots and time? I have the bots set so that if it's 1 player there is 1 bot but as more people join there should be no bots.

The idea of this project is I set what I think are good defaults, then you can customise it yourself for your own server using [custom files](https://github.com/kus/cs2-modded-server?tab=readme-ov-file#custom-files) and you can stay up-to-date with this repo and your files will always overwrite my defaults.

Anyone can do a pull request, then I will accept it if I think it's a good contribution.

**Comment by pnallinger** [comment]
But the Arms Race mode somehow only works on the official maps (ar_baggage & ar_shoots)

I tested both GunGame and Arms Race. Arms Race currently starts a server for 2 min and then switches to a map that doesn't have arms Race.. 

I'll put up an request in a couple of days when I figured out how to do it properly.

**Comment by kus** [comment]
@pnallinger just confirming that with the default setup (this repo) you can play arms race on custom maps.

- I booted my server up
- Typed `!rcon exec ar` in chat
- It changed to `ar_shoots`
- I played through with a bot to the end, it chose a random map from the gg mapgroup and it changed to `fy_pool_day`
- I played through on `fy_pool_day` all the way to the end and it changed to another map from the gg mapgroup

If you don't experience this same behaviour it must be something you have changed on your end.

**Comment by pnallinger** [comment]
Ok then there was an error updating. Sorry. I will test

**Comment by pnallinger** [comment]
clean new install fixed it. but the only thing i did before i changed any config was to update using the last release. Sorry for the inconvenience !! and thx for confirming on your end **kus**!
